# Generated by Django 4.2.10 on 2025-03-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type', models.CharField(choices=[('error', 'Erreur'), ('warning', 'Avertissement'), ('info', 'Information')], default='warning', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Reconnue'), ('resolved', 'Résolue')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='equipment.equipment', verbose_name='Équipement')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
            },
        ),
    ]
