# Generated by Django 4.2.10 on 2025-06-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ping_response_time', models.FloatField(blank=True, help_text='Temps de réponse ping en ms', null=True)),
                ('packet_loss', models.FloatField(blank=True, help_text='Perte de paquets en %', null=True)),
                ('bandwidth_up', models.BigIntegerField(blank=True, help_text='Bande passante montante en bps', null=True)),
                ('bandwidth_down', models.BigIntegerField(blank=True, help_text='Bande passante descendante en bps', null=True)),
                ('cpu_usage', models.FloatField(blank=True, help_text='Utilisation CPU en %', null=True)),
                ('memory_total', models.BigIntegerField(blank=True, help_text='Mémoire totale en bytes', null=True)),
                ('memory_used', models.BigIntegerField(blank=True, help_text='Mémoire utilisée en bytes', null=True)),
                ('disk_total', models.BigIntegerField(blank=True, help_text='Espace disque total en bytes', null=True)),
                ('disk_used', models.BigIntegerField(blank=True, help_text='Espace disque utilisé en bytes', null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('connection_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Bon'), ('fair', 'Moyen'), ('poor', 'Mauvais'), ('offline', 'Hors ligne')], default='good', max_length=20)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Métrique réseau',
                'verbose_name_plural': 'Métriques réseau',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['equipment', '-timestamp'], name='metrics_net_equipme_0b35ee_idx'), models.Index(fields=['timestamp'], name='metrics_net_timesta_f58d52_idx'), models.Index(fields=['is_online'], name='metrics_net_is_onli_5baae9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_warning_threshold', models.FloatField(default=100.0, help_text="Seuil d'avertissement ping en ms")),
                ('ping_critical_threshold', models.FloatField(default=500.0, help_text='Seuil critique ping en ms')),
                ('packet_loss_warning', models.FloatField(default=5.0, help_text="Seuil d'avertissement perte paquets en %")),
                ('packet_loss_critical', models.FloatField(default=20.0, help_text='Seuil critique perte paquets en %')),
                ('cpu_warning_threshold', models.FloatField(default=80.0, help_text="Seuil d'avertissement CPU en %")),
                ('cpu_critical_threshold', models.FloatField(default=95.0, help_text='Seuil critique CPU en %')),
                ('memory_warning_threshold', models.FloatField(default=80.0, help_text="Seuil d'avertissement mémoire en %")),
                ('memory_critical_threshold', models.FloatField(default=95.0, help_text='Seuil critique mémoire en %')),
                ('disk_warning_threshold', models.FloatField(default=80.0, help_text="Seuil d'avertissement disque en %")),
                ('disk_critical_threshold', models.FloatField(default=95.0, help_text='Seuil critique disque en %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='equipment.equipment')),
            ],
            options={
                'verbose_name': "Seuil d'alerte",
                'verbose_name_plural': "Seuils d'alerte",
                'unique_together': {('equipment',)},
            },
        ),
    ]
